module.exports = (mongoose, mongoosePaginate) => {
  var schema = mongoose.Schema(
    {
      valveNo: String,
      tagNo: String,
      valveSection: String,
      valveSerialNo: String,
      valveMake: String,
      valvePurchaseDate: String,
      valvePurchaseValue: String,
      warrantyFinishDate: String,
      serviceDueDate: String,
      valveType: String,
      emergencyShutDownValve: String,
      ifBallValve: String,
      ifButterflyValve: String,
      valveTorque: String,
      butterflyVaneMOC: String,
      butterflyVaneMOCOther: String,
      ifSafetyValve: String,
      setPressure: String,
      overPressure: String,
      backPressure: String,
      relievingPressure: String,
      lineFluid: String,
      serviceType: String,
      lineSize: String, 
      valveSize: String, 
      flow1: String,
      flow1Unit: String,
      flow2: String,
      flow2Unit: String,
      flow3: String,
      flow3Unit: String,
      inletPressure1: String,
      inletPressure2: String,
      inletPressure3: String,
      pressureDifference: String,
      designPressure: String,
      designPressureUnit: String,
      designTemp: String,
      designTempUnit: String,
      viscosity: String,
      viscosityUnit: String,
      specificGravity: String,
      molecularWeight: String,
      actuatorShutoffPressure: String,
      actuatorShutoffPressureUnit: String,
      valveLiftPercentage1: String,
      valveLiftPercentage2: String,
      valveLiftPercentage3: String,
      valveNoise: String,
      designCV: String,
      calculatedCV1: String,
      calculatedCV2: String,
      calculatedCV3: String,
      bodyMOC: String,
      bodyLining: String,
      endConnection: String,
      flangeRating: String,
      valveModelNo: String,
      trimSize: String,
      trimSizeUnit: String,
      trimType: String,
      trimcCharacteristic: String,
      trimMOC: String,
      ballValveSeatMOC: String,
      plugRingsMOC: String,
      seatArrangement: String,
      glandPacking: String,
      bodyBonnetGasket: String,
      valveBonnetType: String,
      bellowSeal: String,
      bellowSealMOC: String,
      leakageClass: String,
      leakageValueAllowed: String,
      actuatorType: String,
      actuatorModel: String,
      fieldReversible: String,
      actuatorTravel: String,
      diaphragMaterial: String,
      airPressureRequired: String,
      airPressureRequiredUnit: String,
      springRange: String,
      springMOC: String,
      positionerType: String,
      modelNoOfPositioner: String,
      ePArea: String,
      aFRMake: String,
      aFRModel: String,
      aFRFilterSize: String,
      aFRFilterMOC: String,
      positionerTransmitter: String,
      positionTransmitterType: String,
      positionTransmitterMake: String,
      positionTransmitterModel: String,
      positionTransmitterArea: String,
      solenoidValveType: String,
      solenoidValveMOC: String,
      solenoidValveArea: String,
      solenoidValveMake: String,
      machNoExceeding: String,
      velocityExceeding: String,
      stelliting: String,
      lapping: String,
      nitriding: String,
      iBR: String,
      failSafeAction: String,
      limitSwitch: String,
      limitSwitchMake: String,
      limitSwitchType: String,
      lastServiceDate: String,
      serviceReminder: String,
      serviceReminderDate: String
    },
    { timestamps: true }
  );

  schema.method("toJSON", function() {
    const { __v, _id, ...object } = this.toObject();
    object.id = _id;
    return object;
  });

  schema.plugin(mongoosePaginate);

  const Rf = mongoose.model("rf", schema);
  return Rf;
};